### ISSUE TITLE
README.md written in Simplified Chinese

### ISSUE THREAD

**Issue by LJxFFFF** [ConvergenceSoftware/ExCamera#1]
Please Help! Thanks in advance.

**Comment by Qujinghua** [comment]
I second that!

**Comment by 1162597506** [comment]
na  wo +1

**Comment by dengaowen** [comment]
Oh my god. Why you so NB?

**Comment by ConvergenceSoftware** [comment]
Well, the Chinese README.md has been uploaded now :) @LJxFFFF @1162597506 @dengaowen @Qujinghua
